### ISSUE TITLE
Handling change in lastPage

### ISSUE THREAD

**Issue by bracke** [mikeu/ember-pagination-links#1]
Hi

The component does not seem to react if the lastPage changes, e.g. because the data being displayed changes.
Is there a way to signal to the component that the lastPage is changed?

**Comment by mikeu** [comment]
Hi @bracke, do you have a sample repo I could look at demonstrating the problem, or even just some screenshots of what you're seeing vs what you expect to see? I've tried to guess at how to replicate the issue, but in my tests so far, a change to the variable passed in to the `lastPage` property does correctly propagate to the component, just based on Ember's data binding.

**Comment by bracke** [comment]
Thats what I expected, but it does not act like that.

``` handlebars
{{log filteredLastPage}}
{{pagination-links
  lastPage=filteredLastPage 
  goToPage=(action 'setPage')
}}
```

When filteredLastPage becomes 8 it switchet correctly to displaying 8 page links.
Then filteredLastPage changes to 1 but the number of page links does not change, it still display 8 page links.

**Comment by bracke** [comment]
Thats what I expected, but it does not act like that in this particular case.

``` handlebars
{{log filteredLastPage}}
{{pagination-links
  lastPage=filteredLastPage 
  goToPage=(action 'setPage')
}}
```

When filteredLastPage is 8, it correctly displays 8 pagination links.
If I afterwards change the filteredLastPage to 1 it does not change the pagination, there still are 8 pagination links instead of the single one I would expect.

The log output in the console is "8" and then "1".

**Comment by mikeu** [comment]
Are you able to show me the controller code that is changing the value of `filteredLastPage` in this example?

Also, what page are you on when the last page changes? In trying to replicate this issue, I have found a bug where if the last page is set to a value less than the currently displayed page, then the pagination links still show up to the current page number. Perhaps if page 8 is currently selected when `filteredLastPage` is changed, that could be the problem you are encountering?

I'll get a fix pushed for that issue soon.

**Comment by mikeu** [comment]
In the meantime, here's an Ember Twiddle showing the last page updating correctly when its underlying value is changed: https://ember-twiddle.com/d70996f5a23a984e3bda0a3d7547bd0f?openFiles=templates.application.hbs

Are you able to modify that so that it demonstrates the issue you're experiencing?

**Comment by bracke** [comment]
Yes:

1. Click on 8.
2. Change lastpage to 1.

**Comment by mikeu** [comment]
OK, so this is exactly the problem I identified above, that only occurs if your current page value is larger than the new last page number. It's easy enough for you to change the current page at the same time as updating the last page, but I agree that the component should probably have a default behaviour different from what it does now, and take care of it for you in most instances.

What behaviour would you expect in this case? The component could reset to page 1 when the last page is less than the current page, or it could reset to the new last page, or it could do something else I haven't thought of...

**Comment by bracke** [comment]
I would expect it to reset to page 1, anything else requires knowledge about the content in the list.

**Comment by mikeu** [comment]
OK, thanks for the input. I'll take a look at what's involved and report back. It also wouldn't take any knowledge of the list content to go to the last page.

The trouble is, I think the appropriate behaviour depends not on the list content, but on the action that causes it to get shorter. If you're on the last page and deleting entries, then it makes sense to update to be on the new last page. If you're filtering to a subset of the original list, then it probably makes sense to jump to the first page. This is why the user of the component has access to get and set the current page, so that you can update it however is appropriate for your use case.

**Comment by bracke** [comment]
Yes, in my case its filtering :-)

Perhaps mentioning those to cases and their solution on the Github page / readme would be enough?

**Comment by mikeu** [comment]
I pushed an update that allows an optional `overflow` parameter. This will let you tell the component to jump to either the first or last page whenever the current page is beyond the last page. The readme is also updated to reflect this, and to describe how you can handle the situation yourself if you don't want to use the built-in behaviour.
